title: Mi Sitio con Jekyll
description: Documentación dinámica
baseurl: "/hugocasildo" # Nombre exacto de tu repositorio
url: "https://hugocasildo.github.io" # Reemplaza <TU_USUARIO> con tu usuario
collections:
  docs:
    output: true
    permalink: /docs/:path/
