title: Mi Sitio con Jekyll
description: Sitio con navegación lateral dinámica
baseurl: "" # Deja vacío si no usas un subdirectorio
url: "https://hugocasildo.github.io"
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /docs/:path/
